erDiagram
    usuarios {
        INT id PK
        VARCHAR nombre
        VARCHAR apellido
        VARCHAR email UK
        VARCHAR password
        DATETIME created_at
        DATETIME updated_at
    }
