
Skillnest (FullStack Python) - 2026
Próximas entregas
Se entrega hoy
2.- Creación de ERD + insertar valores en BD generada. (Sistema Gestión de usuarios - Mensajes)

Publicado por DANY HERNANDEZ GONZALEZ
DANY HERNANDEZ GONZALEZ
Fecha de creación: 12:1712:17
Base de datos Sistema de mensajes
Mostrando 
ERD_SISTEMA_DE_MENSAJES.png
database.sql
SQL

assignment
Tarea: "2.- Creación de ERD + insertar valores en BD generada. (Sistema Gestión de usuarios - Mensajes)"
DANY HERNANDEZ GONZALEZ ha publicado una nueva tarea: 2.- Creación de ERD + insertar valores en BD generada. (Sistema Gestión de usuarios - Mensajes)
Fecha de creación: 12:0812:08
assignment
Tarea: "1.- Administración de usuarios (Templates) - 1 Parte"
DANY HERNANDEZ GONZALEZ ha publicado una nueva tarea: 1.- Administración de usuarios (Templates) - 1 Parte
Fecha de creación: 18 may18 may

Publicado por DANY HERNANDEZ GONZALEZ
DANY HERNANDEZ GONZALEZ
Fecha de creación: 18 may18 may
Contestar encuesta:
Pulso Escolar
https://encuestas.pulsoescolar.com/?ac=bm5-5sy-8wu

assignment
Tarea: "5.- Aplicando todo lo aprendido en clases (Guía con nota)"
DANY HERNANDEZ GONZALEZ ha publicado una nueva tarea: 5.- Aplicando todo lo aprendido en clases (Guía con nota)
Fecha de creación: 12 may12 may
assignment
Tarea: "(Core) Suscripción a plataforma de streaming "
DANY HERNANDEZ GONZALEZ ha publicado una nueva tarea: (Core) Suscripción a plataforma de streaming
Fecha de creación: 11 may11 may (Última modificación: 11 may)
book
Material: "4.- Guía OOP - Clases, Atributos de Clase, Métodos de clase, de instancia y estáticos. "
DANY HERNANDEZ GONZALEZ ha publicado nuevo material: 4.- Guía OOP - Clases, Atributos de Clase, Métodos de clase, de instancia y estáticos.
Fecha de creación: 7 may7 may
assignment
Tarea: "***Evaluación de Programación: Funciones en Python con Menú Interactivo Colaborativo"
DANY HERNANDEZ GONZALEZ ha publicado una nueva tarea: ***Evaluación de Programación: Funciones en Python con Menú Interactivo Colaborativo
Fecha de creación: 4 may4 may (Última modificación: 4 may)
assignment
Tarea: "3.- Repaso de funciones (práctica prueba)"
DANY HERNANDEZ GONZALEZ ha publicado una nueva tarea: 3.- Repaso de funciones (práctica prueba)
Fecha de creación: 29 abr29 abr (Última modificación: 29 abr)

Publicado por DANY HERNANDEZ GONZALEZ
DANY HERNANDEZ GONZALEZ
Fecha de creación: 28 abr28 abr
Concurso:
Tu Polerón Generacional con la Autónoma - U Autónoma
https://admision.uautonoma.cl/concurso-polerones/?utm_source=mailing&utm_medium=mailing&utm_campaign=concurso_polerones_2etapa

assignment
Tarea: "(Core) Funciones intermedias en Python"
DANY HERNANDEZ GONZALEZ ha publicado una nueva tarea: (Core) Funciones intermedias en Python
Fecha de creación: 23 abr23 abr
assignment
Tarea: "2.- (Práctica) Funciones básicas 1 y 2"
DANY HERNANDEZ GONZALEZ ha publicado una nueva tarea: 2.- (Práctica) Funciones básicas 1 y 2
Fecha de creación: 22 abr22 abr (Última modificación: 23 abr)
assignment
Tarea: "(Core) Bucles for: básico 1 "
DANY HERNANDEZ GONZALEZ ha publicado una nueva tarea: (Core) Bucles for: básico 1
Fecha de creación: 20 abr20 abr (Última modificación: 20 abr)
assignment
Tarea: "1.- Ejercicios para Python"
DANY HERNANDEZ GONZALEZ ha publicado una nueva tarea: 1.- Ejercicios para Python
Fecha de creación: 9 abr9 abr
Skillnest (FullStack Python) - 2026-Classroom
-- MySQL Script generated by MySQL Workbench
-- Tue May 19 12:15:31 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistema_mensajes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema_mensajes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema_mensajes` DEFAULT CHARACTER SET utf8 ;
USE `sistema_mensajes` ;

-- -----------------------------------------------------
-- Table `sistema_mensajes`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_mensajes`.`roles` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre_rol` VARCHAR(50) NOT NULL,
  `descripcion_rol` VARCHAR(300) NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP, -- CURRENT_TIMESTAMP: Valor fecha y hora actual
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  `deleted` TINYINT(1) DEFAULT 0, 
  -- Borrado lógico - No se borra el registro fisicamente
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;

-- DIEGO MUERE- DEBEMOS SACARLO DEL SISTEMA. BORRADO FÍSICO DELETE FROM USUARIO
-- CON DELETE EL DATO DEJA DE EXISTIR - NO SE PUEDE RECUPERAR
-- EN CAMBIO CON BORRADO LÓGICO (campo deleted activo - deleted 1))
-- PODEMOS OCULTAR EL USUARIO PARA QUE EL CLIENTE NO LO VEA
-- PERO NO SALE DEL SISTEMA.

-- -----------------------------------------------------
-- Table `sistema_mensajes`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_mensajes`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP, -- CURRENT_TIMESTAMP: Valor fecha y hora actual
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  `deleted` TINYINT(1) DEFAULT 0, 
  `id_rol` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `nombre_usuario_UNIQUE` (`nombre_usuario` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_usuarios_roles_idx` (`id_rol` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_roles`
    FOREIGN KEY (`id_rol`)
    REFERENCES `sistema_mensajes`.`roles` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_mensajes`.`mensajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_mensajes`.`mensajes` (
  `id_mensaje` INT NOT NULL AUTO_INCREMENT,
  `contenido` TEXT NOT NULL,
 `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP, -- CURRENT_TIMESTAMP: Valor fecha y hora actual
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  `deleted` TINYINT(1) DEFAULT 0, 
  `emisor` INT NOT NULL,
  `receptor` INT NOT NULL,
  PRIMARY KEY (`id_mensaje`),
  INDEX `fk_mensajes_usuarios1_idx` (`emisor` ASC) VISIBLE,
  INDEX `fk_mensajes_usuarios2_idx` (`receptor` ASC) VISIBLE,
  CONSTRAINT `fk_mensajes_usuarios1`
    FOREIGN KEY (`emisor`)
    REFERENCES `sistema_mensajes`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mensajes_usuarios2`
    FOREIGN KEY (`receptor`)
    REFERENCES `sistema_mensajes`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_mensajes`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_mensajes`.`comentarios` (
  `id_comentario` INT NOT NULL AUTO_INCREMENT,
  `contenido` TEXT NOT NULL,
 `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP, -- CURRENT_TIMESTAMP: Valor fecha y hora actual
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  `deleted` TINYINT(1) DEFAULT 0, 
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_comentario`),
  INDEX `fk_comentarios_usuarios1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_comentarios_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `sistema_mensajes`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- insertar datos en tablas (5 registros)
USE sistema_mensajes;
INSERT INTO roles(nombre_rol, descripcion_rol) 
VALUES ("admin", "control total"),
("usuario_comun", "permisos administrativos básicos"),
("invitado", "usuario temporal con permisos limitados");
INSERT INTO usuarios(nombre_usuario, password_hash, email, id_rol) 
VALUES("Randy123", "randy123", "randy@gmail.com", 2),
("akon123", "akon123", "akon@gmail.com", 1),
("tete123", "tete123", "tete@gmail.com", 2),
("anne123", "anne123", "annerill@gmail.com", 3),
("arael123", "arael123", "arael@gmail.com", 3);

INSERT INTO comentarios( ) VALUES();
INSERT INTO mensajes()VALUES;
