CREATE DATABASE IF NOT EXISTS esquema_tacos;

USE esquema_tacos;

CREATE TABLE IF NOT EXISTS tacos (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    tortilla VARCHAR(45),
    guiso VARCHAR(45),
    salsa VARCHAR(45),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
